version: '3'
services:
  mysql:
    container_name: mysql
    build: ../docker/mysql
    environment:
      MYSQL_DATABASE: gym
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - mysql_gym_db:/var/lib/mysql
  backend:
    container_name: backend
    build: ./spring
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ../spring_project:/srv:cached
    working_dir: /srv
    environment:
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://mysql:3306/gym"
      spring.datasource.username: "user"
      spring.datasource.password: "password"
volumes:
  mysql_gym_db:
    driver: local